default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  #port: 3307
  socket: /var/run/mysqld/mysqld.sock
  database: cats-db
  username: user
  password: password

development:
  <<: *default

test:
  <<: *default
  host: test_db
  #port: 3307
  database: test_cats-db
  username: test_user
  password: test_password

production:
  <<: *default
  